change-template: '- #$NUMBER $TITLE @$AUTHOR'
sort-direction: ascending
categories:
  - title: 'Item1'
    labels: 
      - 'test'

  - title: 'Item1'
    labels:
      - 'test'
      - 'test2'
template: |
  $CHANGES