name: 'waitforjob'
description: 'Wait for a job to finish'
inputs:
  job:
    description: 'The name of the job to wait for'
    required: true
  timeout:
    description: 'number of milliseconds to wait between retries'
    required: false
    default: 5
  retry-limit:
    description: 'number of maximum retries'
    required: false
    default: 3
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
runs:
  using: "composite"
  steps: 
    - shell: bash
      run: |
        retries=1
        conclusion="";
        status="";

        while true; do 
          result=$(curl -sSL -f https://api.github.com/repos/ludeeus/ROOT/commits/6ff53563050c7b9355e16b39005d7a50303da9c6/check-runs | jq --arg test ${{inputs.job}} '[.check_runs | .[] |select(.name | contains($test))][0]')
          conclusion=$(echo $result | jq -r .conclusion)
          status=$(echo $result | jq -r .status)
          echo "Try: $retries/${{inputs.retry-limit}}"
          echo "Status: $status"
          echo "Conclusion: $conclusion"
          echo

          if [ "$status" != "completed" ] || [ "$retries" == "${{inputs.retry-limit}}" ]; then
            break
          else
            sleep ${{inputs.timeout}}
            retries=$(( $retries + 1 ))
          fi
        done

        if [ "$conclusion" != "success" ]; then
          exit 1
        fi