name: Workflow 1

on:
  push:
    branches:
      - test3

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - run: echo $GITHUB_SHA


      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const res = await github.request('GET /repos/{owner}/{repo}/commits/{ref}/statuses', {
              owner: 'octocat',
              repo: 'hello-world',
              ref: '${{github.sha}}'
            })
            console.log(res)