name: Workflow 1

on:
  push:
    branches:
      - test3

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - run: echo $GITHUB_SHA


      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const target = "job1";
            let conclusion;
            const res = await github.request('GET /repos/{owner}/{repo}/commits/{ref}/check-runs', {
              owner: 'ludeeus',
              repo: 'ROOT',
              ref: '${{github.sha}}'
            });
            console.dir(res);
            conclusion = res.data.check_runs.find((res) => res.name = target).conclusion
            console.log(conclusion);

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - run: echo $GITHUB_SHA


      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            function timeout(ms) {
                return new Promise(resolve => setTimeout(resolve, ms));
            }
            const target = "job1";
            let conclusion;
            let status;
            while (status !== "completed") {
              await timeout(5000)
              const res = await github.request('GET /repos/{owner}/{repo}/commits/{ref}/check-runs', {
                owner: 'ludeeus',
                repo: 'ROOT',
                ref: '${{github.sha}}'
              });
              console.dir(res.data.check_runs);
              conclusion = res.data.check_runs.find((res) => res.name = target).conclusion;
              status = res.data.check_runs.find((res) => res.name = target).status;  
            }

            console.log(status, conclusion);