name: Release Drafter

on:
  push:
    branches:
      - test3

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - run: printenv