
name: Deploy

on:
  pull_request:
    branches:
      - master
    types:
      - labeled
      - unlabeled
      - synchronize

jobs:
  labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - name: Check labels
        env:
          EXPECTED_LABELS: bug,test
        run: |
          labels=$(jq -r '.pull_request.labels[] | .name' ${{github.event_path }})
          for label in ${EXPECTED_LABELS//,/ }; do
            echo "Checking for '$i' label"
            if [[ $label == *"$labels"* ]]; then
               exit 0
            fi
          done
          exit 1
