
name: Deploy

on:
  pull_request:
    branches:
      - master

jobs:
  labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - name: Check labels
        run: |
          echo ${{ github.event.pull_request.labels[*].name.some(entry => ['bug'].contains(entry)) }}
