
name: Deploy

on:
  pull_request:
    branches:
      - master
    types:
      - synchronize

jobs:
  labels:
    name: Check labels
    runs-on: ubuntu-latest
    strategy:
      matrix:
        handler:
          - name: "example"
          - name: "other"
            some_val: "sdassa"
    steps:
      - name: Get name
        run: echo ${{ matrix.handler.name }}
      - name: Get ref
        run: echo ${{ github.event_name == 'release' && github.event.release.tag_name || github.ref }}
      - name: Get some_val
        if: ${{ github.event_name == 'pull_request' && matrix.handler.some_val }}
        run: echo ${{ matrix.handler.some_val }}
