
name: Deploy

on:
  pull_request:
    branches:
      - master
    types:
      - labeled
      - unlabeled
      - synchronize

jobs:
  labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - name: Check labels
        run: |
          for i in bug test; do
            echo "Checking for $i label"
            if [[ ${{ contains(github.event.issue.labels.*.name, '$i') }} == "true" ]]; then
               exit 0
            fi
          done
          exit 1
