
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  changes:
    name: 'Check for worker changes'
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.filter.outputs.all }}
      mqtt: ${{ steps.filter.outputs.mqtt }}


    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2.4.2
        id: filter
        with:
          filters: |
            all:
              - '.github/workflows/**'
            mqtt:
              - 'mqtt/**'


  deploy-mqtt:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.all == 'true' || needs.changes.outputs.${{matrix.app}} == 'true'}}
    strategy:
      matrix:
        app: ['mqtt']
    steps:
      - uses: actions/checkout@v2
