
name: Deploy

on:
  pull_request:
    branches:
      - master

jobs:
  labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - name: Check labels
        run: |
          for i in bug test; do
             if [[ ${{ contains(github.event.issue.labels.*.name, '$i') }} ]]; then
                exit 0
             fi
          done
          exit 1
