
name: Deploy

on:
  pull_request:
    branches:
      - master

jobs:
  create:
    name: Create
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        category:
          - apple
          - orange
          - banana
    steps:
      - run: mkdir -p outputdata/${{matrix.category}}
      - run: |
          echo "{'changed_pct': 30}" > outputdata/${{matrix.category}}/summary.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: ${{ matrix.category }}
          path: |
            outputdata/${{ matrix.category }}
          if-no-files-found: warn
          retention-days: 3

  validate:
    name: Validate
    runs-on: ubuntu-latest
    needs: create
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          path: outputdata
      
      - name: Combined summary
        uses: actions/github-script@v7.0.1
        id: summary
        with:
          script: |
            const combined = {};
            const globber = await glob.create('outputdata/**', { withFileTypes: true })
            for await (const file of globber.globGenerator()) {
              console.log(file)
            }
