
name: Deploy

on:
  pull_request:
    branches:
      - master

jobs:
  create:
    name: Create
    runs-on: ubuntu-latest
    outputs:
      summary: ${{ steps.summary.outputs.summary }}
    strategy:
      fail-fast: false
      matrix:
        category:
          - apple
          - orange
          - banana
    steps:
      - id: summary
        run: |
          echo "summary={"changed_pct": 30}" >> $GITHUB_OUTPUT

  validate:
    name: Create
    runs-on: ubuntu-latest
    needs: create
    strategy:
      fail-fast: false
      matrix:
        category:
          - apple
          - orange
          - banana
    steps:
      - run: echo "${{ fromJson(needs.create.outputs.summary) }}"
