
name: Deploy

on:
  pull_request:
    branches:
      - master

jobs:
  create:
    name: Create
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        category:
          - apple
          - orange
          - banana
    steps:
      - run: mkdir -p outputdata/${{matrix.category}}
      - run: |
          echo '{"changed_pct": 30, "category": "${{matrix.category}}"}' > outputdata/${{matrix.category}}/summary.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: ${{ matrix.category }}
          path: |
            outputdata/${{ matrix.category }}
          if-no-files-found: warn
          retention-days: 3

  validate:
    name: Validate
    runs-on: ubuntu-latest
    needs: create
    outputs:
      summaries: ${{ steps.summaries.outputs.summaries }}
      categories: ${{ steps.summaries.outputs.categories }}
      environment: ${{ steps.summaries.outputs.environment }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          path: outputdata
      
      - name: Combined summary
        uses: actions/github-script@v7.0.1
        id: summaries
        with:
          script: |
            const script = require('.github/workflows/scripts/generate_summary.js')
            script(core)
            


  use:
    name: "[[${{ matrix.category }}]]Use (${{ needs.validate.outputs.environment }})"
    runs-on: ubuntu-latest
    needs: validate 
    environment: "${{ fromJson(needs.validate.outputs.categories)[matrix.category] }}"
    strategy:
      matrix:
        category: ${{ fromJson(needs.validate.outputs.categories) }}
    steps:
      - run: |
          echo "${{ toJson(fromJson(needs.validate.outputs.summaries)[matrix.category]) }}"
      