name: "use-details"

on:
  pull_request:
    branches:
      - master

permissions: {}


jobs:
  preflight:
    if: ${{ github.repository == 'ludeeus/ROOT' }}
    runs-on: ubuntu-latest
    name: Preflight
    steps:
      - name: Summary
        run: |
          echo "<details><summary>${{matrix.entry.repository}}</summary>" >> $GITHUB_STEP_SUMMARY
          docker logs hacs_action_local >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

