name: "use-details"

on:
  pull_request:
    branches:
      - master

permissions: {}


jobs:
  preflight:
    if: ${{ github.repository == 'ludeeus/ROOT' }}
    runs-on: ubuntu-latest
    name: Preflight
    steps:
      - name: Validation preflight
        env:
          ACTOR: ${{ github.actor }}
          REF: ${{ github.ref }}
          event_name: ${{ github.ref }}
        run: |
          echo "**Start:**  $(date)" >> $GITHUB_STEP_SUMMARY
          echo "**Actor:**  $ACTOR" >> $GITHUB_STEP_SUMMARY
          echo "**Actor:**  $event_name" >> $GITHUB_STEP_SUMMARY

