name: "use-details"

on:
  pull_request:
    branches:
      - master

permissions: {}


jobs:
  preflight:
    if: ${{ github.repository == 'ludeeus/ROOT' }}
    runs-on: ubuntu-latest
    name: Preflight
    steps:
      - name: Validation preflight
        env:
          ACTOR: ${{ github.actor }}
          EVENT_NAME: ${{ github.event_name }}
          REF_NAME: ${{ github.ref_name }}
          REF: ${{ github.ref }}
          SHA: ${{ github.sha }}
        run: |
          echo "**Start:** $(date)" >> $GITHUB_STEP_SUMMARY
          echo "**Actor:** $ACTOR" >> $GITHUB_STEP_SUMMARY
          echo "**Event:** $EVENT_NAME" >> $GITHUB_STEP_SUMMARY
          echo "**Ref name:** $REF_NAME" >> $GITHUB_STEP_SUMMARY
          echo "**Ref:** $REF" >> $GITHUB_STEP_SUMMARY
          echo "**SHA:** $SHA" >> $GITHUB_STEP_SUMMARY

