name: "use-details"

on:
  pull_request:
    branches:
      - master

permissions: {}

jobs:
  preflight:
    if: ${{ github.repository == 'ludeeus/ROOT' }}
    runs: ubuntu-latest
    name: Preflight
    steps: []

        
