name: "use-details"

on:
  pull_request:
    branches:
      - master

permissions: {}


jobs:
  preflight:
    if: ${{ github.repository == 'ludeeus/ROOT' }}
    runs-on: ubuntu-latest
    name: Preflight
    steps:
      - name: Run docker
        run: |
          docker run --name hello_world \
            hello-world:latest
      - name: Summary
        run: |
          echo "<details><summary>${{github.repository}}</summary>" >> $GITHUB_STEP_SUMMARY
          docker logs hello_world >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

